KathleenYruegas/truck-trackr-be

app/models/brewery.rb, db/migrate/20181220213506_create_breweries.rb, db/schema.rb, db/seeds.rb, spec/factories/breweries.rb, spec/models/brewery_spec.rb
__x__ Reviewed
- [] Bug Fix
* description: Adds the brewery model and the brewery table to the db.  Sets up seeds file for breweries and seeds.
closes story #20 
=> Brewery model

Gemfile, Gemfile.lock, app/controllers/api/v1/breweries_controller.rb, app/controllers/api/v1/food_trucks_controller.rb, app/serializers/brewery_index_serializer.rb, app/serializers/brewery_serializer.rb, config/routes.rb, spec/rails_helper.rb, spec/requests/brewery_request_spec.rb
__x__ Reviewed
- [] Bug Fix
* description: Creates endpoint for breweries index. Creates serializer to display just the names for the index call.
closes story #8 
https://media.giphy.com/media/LTYT5GTIiAMBa/giphy.gif
=> All breweries#8

app/controllers/api/v1/breweries_controller.rb, app/serializers/brewery_show_serializer.rb, config/routes.rb, spec/requests/brewery_request_spec.rb
____ Reviewed
- [] Bug Fix
Adds happy and sad paths for brewery show
closes story #9 
=> 9 get brewery show master aq

app/controllers/api/v1/food_trucks_controller.rb, app/serializers/food_truck_index_serializer.rb, app/serializers/food_truck_show_serializer.rb, app/serializers/truck_city_serializer.rb, config/routes.rb, spec/requests/truck_resource_requests_spec.rb
____ Reviewed
- [] Bug Fix
Adds food truck show API endpoint functionality
closes story #7 
=> 7 food truck show 6 fix cities table aq

app/controllers/api/v1/breweries_controller.rb, config/routes.rb, db/schema.rb, spec/requests/brewery_request_spec.rb
____ Reviewed
- [] Bug Fix
Adds brewery update functionality
closes story #34 
=> 34 put update brewery master aq

app/controllers/api/v1/breweries_controller.rb, config/routes.rb, db/schema.rb, spec/requests/brewery_request_spec.rb
____ Reviewed
- [] Bug Fix
Adds brewery delete api endpoint functionality
closes story #37 
=> 37 delete breweries 34 put breweries aq

app/controllers/api/v1/breweries_controller.rb, app/controllers/api/v1/food_trucks_controller.rb, config/routes.rb, db/schema.rb, spec/factories/food_trucks.rb, spec/requests/brewery_request_spec.rb, spec/requests/truck_resource_requests_spec.rb
___x_ Implemented
____ Reviewed
- [] Bug Fix
adds food truck delete api endpoint
closes story #35 
=> 35 put food truck 37 delete brewery aq

app/controllers/api/v1/breweries_controller.rb, app/controllers/api/v1/food_trucks_controller.rb, config/routes.rb, db/schema.rb, spec/factories/food_trucks.rb, spec/requests/brewery_request_spec.rb, spec/requests/truck_resource_requests_spec.rb
__x_ Implemented
____ Reviewed
- [] Bug Fix
Adds Food Truck delete endpoint
=> 38 delete truck 35 put truck aq

app/controllers/api/v1/open_dates_controller.rb, config/routes.rb, db/migrate/20181229173419_change_booked_to_have_default_in_open_dates.rb, db/schema.rb, db/seeds.rb, spec/requests/truck_open_dates_requests_spec.rb
__x__ Reviewed
- [] Bug Fix
* description: Adds post for food_trucks/open_dates
closes story #13 
=> Add food truck open date#13

app/controllers/api/v1/brewery_events_controller.rb, app/models/brewery.rb, app/models/brewery_event.rb, app/serializers/brewery_event_serializer.rb, app/serializers/brewery_show_serializer.rb, config/routes.rb, db/migrate/20181228225710_create_brewery_events.rb, db/schema.rb, spec/factories/brewery_events.rb, spec/models/brewery_event_spec.rb, spec/requests/brewery_events_request_spec.rb, spec/requests/brewery_request_spec.rb
____ Reviewed
- [] Bug Fix
--Adds brewery events api endpoint
--First successful rebase!!!
closes story #44 
=> 44 get brewery events index master aq

app/controllers/api/v1/brewery_events_controller.rb, app/models/brewery.rb, app/models/brewery_event.rb, app/serializers/brewery_event_serializer.rb, app/serializers/brewery_show_serializer.rb, config/routes.rb, db/migrate/20181228225710_create_brewery_events.rb, db/schema.rb, spec/factories/brewery_events.rb, spec/models/brewery_event_spec.rb, spec/requests/brewery_events_request_spec.rb, spec/requests/brewery_request_spec.rb
____ Reviewed
- [] Bug Fix
Adds brewery event creation api endpoint
closes story #4 
=> 4 post brewery events 44 get brewery events aq

app/controllers/api/v1/brewery_events_controller.rb, app/models/brewery.rb, app/models/brewery_event.rb, app/serializers/brewery_event_serializer.rb, app/serializers/brewery_show_serializer.rb, config/routes.rb, db/migrate/20181228225710_create_brewery_events.rb, db/schema.rb, spec/factories/brewery_events.rb, spec/models/brewery_event_spec.rb, spec/requests/brewery_events_request_spec.rb, spec/requests/brewery_request_spec.rb
____ Reviewed
- [] Bug Fix
Completes functional PUT brewery event api end point
closes story #47 
=> 47 put brewery events 4 post brewery event aq

app/controllers/api/v1/brewery_events_controller.rb, app/models/brewery.rb, app/models/brewery_event.rb, app/serializers/brewery_event_serializer.rb, app/serializers/brewery_show_serializer.rb, config/routes.rb, db/migrate/20181228225710_create_brewery_events.rb, db/schema.rb, spec/factories/brewery_events.rb, spec/models/brewery_event_spec.rb, spec/requests/brewery_events_request_spec.rb, spec/requests/brewery_request_spec.rb
____ Reviewed
- [] The code will run locally
- [] Bug Fix
Adds delete brewery event api end point
closes story #5 
=> 5 delete brewery event 47 put brewery event aq

app/controllers/api/v1/breweries_controller.rb, app/controllers/api/v1/food_trucks_controller.rb, app/controllers/api/v1/open_dates_controller.rb, config/routes.rb, spec/requests/brewery_request_spec.rb, spec/requests/truck_open_dates_requests_spec.rb
__x__ Reviewed
- [] Bug Fix
* description: Adds update action for the open_dates
closes story #
=> Put food truck open date

app/controllers/api/v1/open_dates_controller.rb, config/routes.rb, spec/requests/truck_open_dates_requests_spec.rb
__x__ Reviewed
- [] Bug Fix
* description: Adds ability to delete an open date.
closes story #
=> Delete open date#11

app/controllers/api/v1/open_dates_controller.rb, config/routes.rb, spec/requests/truck_open_dates_requests_spec.rb
__x__ Reviewed
- [] Bug Fix
* description: Adds show page endpoint for open dates resource.
closes story #
- [] I have fully tested my code
=> Show page food truck open date

app/controllers/api/v1/brewery_events_controller.rb, spec/requests/brewery_events_request_spec.rb
____ Reviewed
- [] Bug Fix
Adds brewery event show api end point 
closes story #54 
=> 54 get brewery events show master aq

Gemfile, config/application.rb
____ Wrote Tests
____ Implemented
____ Reviewed
- [] All Tests are Passing
- [] The code will run locally
- [] New feature
- [] Bug Fix
* description
closes story #
- [] This broke nothing
- [] My code has no unused/commented out code
- [] I have fully tested my code
=> Adds cors config.

app/models/brewery.rb, app/models/food_truck.rb, spec/requests/brewery_request_spec.rb, spec/requests/truck_resource_requests_spec.rb
__x__ Reviewed
- [] New feature
* description: Allows a truck or brewery to be deleted.
closes story #
=> Fix delete

.rspec, app/controllers/api/v1/breweries_controller.rb, app/controllers/api/v1/brewery_events_controller.rb, app/controllers/api/v1/food_trucks_controller.rb, app/controllers/api/v1/open_dates_controller.rb, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/models/brewery.rb, app/models/food_truck.rb, config/application.rb, config/routes.rb, db/migrate/20190101004635_add_uid_to_food_trucks_and_breweries.rb, db/migrate/20190101041538_adduid_to_breweries_and_food_truck.rb, db/schema.rb, db/seeds.rb, spec/factories/breweries.rb, spec/factories/food_trucks.rb, spec/models/brewery_spec.rb, spec/models/food_truck_spec.rb, spec/requests/brewery_events_request_spec.rb, spec/requests/brewery_request_spec.rb, spec/requests/login_requests_spec.rb, spec/requests/truck_open_dates_requests_spec.rb, spec/requests/truck_resource_requests_spec.rb
__x_ Implemented
____ Reviewed
- [] Bug Fix
Adds Authentication functionality for API end points
closes story #3 
=> Authentication session

app/controllers/api/v1/brewery_events_controller.rb, app/mailers/application_mailer.rb, app/mailers/brewery_event_notifier_mailer.rb, app/models/food_truck.rb, app/views/brewery_event_notifier_mailer/broadcast.html.erb, app/views/brewery_event_notifier_mailer/broadcast.text.erb, config/environments/development.rb, spec/models/food_truck_spec.rb
____ Reviewed
- [] Bug Fix
Adds basic mailer functionality
Adds mailcatcher and configs
Working (Manually tested thru mailcatcher)
closes story #
=> Setup mailer master aqky

.gitignore, Gemfile, Gemfile.lock, config/environments/production.rb
____ Reviewed
- [] Bug Fix
Adds SendGrid config
closes story #
=> Sendgrid implementation master aqky

app/controllers/api/v1/food_trucks_controller.rb, app/serializers/city_serializer.rb, spec/requests/truck_resource_requests_spec.rb
____ Reviewed
- [] New feature
Includes associated cities info in truck show end point
closes story #
=> 67 Includes associated cities info in truck show end point

app/controllers/sessions_controller.rb, spec/requests/login_requests_spec.rb
__x__ Reviewed
- [] Bug Fix
* description: Upon login, response includes object of logged in account.
closes story #
=> Adjust login

app/controllers/sessions_controller.rb, config/routes.rb, spec/requests/session_request_spec.rb
__x__ Reviewed
- [] Bug Fix
* description: Allows for a successful or unsuccessful status code for "login"
closes story #
=> Revamp login

app/controllers/api/v1/breweries_controller.rb, app/controllers/api/v1/food_trucks_controller.rb, spec/requests/brewery_request_spec.rb, spec/requests/truck_resource_requests_spec.rb
____ Wrote Tests
____ Reviewed
- [] New feature
Changes brewery & truck show controllers to include events & dates info in serializer
closes story #
- [x I have fully tested my code
=> Includes belongs to data brewery & truck show aq

config/newrelic.yml
____ Wrote Tests
____ Implemented
____ Reviewed
- [] All Tests are Passing
- [] The code will run locally
- [] Bug Fix
* description: Adds config file for newrelic.
closes story #
- [] This broke nothing
- [] My code has no unused/commented out code
- [] I have fully tested my code
=> Adds newrelic config
